[build]
# The index HTML file to drive the bundling process.
target = "trunk.html"
dist="dist"
public_url = "https://esimkowitz.github.io/dev-widgets/"

# We need to build the Rust code before Trunk runs to ensure build.rs can download Bootstrap and compile the Sass.
[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["build", "--target", "wasm32-unknown-unknown", "--release"]